### ISSUE TITLE
Dependency with different type (pom instead of jar)

### ISSUE THREAD

**Issue by andreas-mausch** [holgerbrandl/kscript#155] opened 2018-09-05 11:22 UTC
Hi there,

I've noticed two things.

First, I think there is a bug in https://github.com/holgerbrandl/kscript/blob/10a9da1185ea9f637c3822ef99bd31038645a470/src/main/kotlin/kscript/app/DependencyUtil.kt#L50 (should be index 3 instead of 2)

And second, is there a way to depend on this:

```
<dependency>
    <groupId>org.javamoney</groupId>
    <artifactId>moneta</artifactId>
    <version>1.3</version>
    <type>pom</type>
</dependency>
```

So, having a different type than jar?
I've tried "org.javamoney:moneta:1.3:pom" but this was failing because of the error above.

Andreas

**Comment by holgerbrandl** [comment] 2018-09-05 14:02
Thanks for the pointer. I've fixed the array access already.

The problem is that maven also for may more options that gradle artifact ids. See https://maven.apache.org/pom.html#POM_Relationships
I don't now how these all are mapped into gradle artifact ids. Do you have any pointer?

With our current schema we have `groupId:artifactId:version[:classifier]`. I'm not sure about how to  correctly squeeze in the `type` here?

**Comment by andreas-mausch** [comment] 2018-09-05 15:30
I've tried it in gradle, since you use "gradle-style locators".
Interestingly, this is the result:
- "org.javamoney:moneta:1.3" - only one which works
- "org.javamoney:moneta:1.3:jar" -> Could not find moneta-jar.jar (org.javamoney:moneta:1.3)
- "org.javamoney:moneta:1.3:pom" -> Could not find moneta-pom.jar (org.javamoney:moneta:1.3)
- "org.javamoney:moneta:1.3@jar" -> Could not find moneta.jar (org.javamoney:moneta:1.3)
- "org.javamoney:moneta:1.3@pom" -> Gives an error at compile time: package org.javamoney.moneta does not exist
- I get the same with the longer version (as officially suggested here: https://github.com/JavaMoney/jsr354-ri), so my project setup is probably wrong.
compile group: 'org.javamoney', name: 'moneta', version: '1.3', ext: 'pom'

So I think "org.javamoney:moneta:1.3@pom" would be the way to go, would be great if you could support it.

**Comment by andreas-mausch** [comment] 2018-09-05 15:56
Just a general idea, now there is also #156 and you probably don't want to rewrite gradle itself: Have you thought about using a build.gradle instead of a pom.xml and switch to gradle completely? Then you wouldn't have to support all those special cases yourself.

**Comment by holgerbrandl** [comment] 2018-09-05 19:12
Yes, moving away von maven to gradle would be more consistent. But I wonder if it would faster/slower compared to our current maven solution.

However, I'm not sure if this would immediately solve your problem since we could still not map our current annotation-schema `groupId:artifactId:version[:classifier]` to 
```
compile group: 'org.javamoney', name: 'moneta', version: '1.3', ext: 'pom'
```
With a new `@DependsOn` different annotation in `kscript`  we could map more specific dependency attributes, but this would break backwards compatibility.

I think the most pragmatic solution would be extend the pattern with either `@<type>` or something similar and map it to a maven pom-xml-tag accordingly.

I struggle a bit to come up with a reproducable example. When resolving your pom-dependendy in a test-project, no jars are added.
![image](https://user-images.githubusercontent.com/200952/45115301-b9a60c80-b14f-11e8-9c67-7f256229e1e9.png)
How can I test if the dependency was resolved correctly?

**Comment by andreas-mausch** [comment] 2018-09-05 19:33
I 100% agree on the pragmatic solution for short-term.

On the no jar added: As mentioned above, I'm also having trouble to make it work with gradle. However, in a maven project it works for me, so it might be an issue of this specific lib or even gradle not resolving transitive dependencies correctly?! Not really sure tho.

But this shouldn't bother us too much, in the end the goal should be to have this in the pom:
```
<dependency>
    <groupId>org.javamoney</groupId>
    <artifactId>moneta</artifactId>
    <version>1.3</version>
    <type>pom</type>
</dependency>
```
and it will work.

Here is the shortest kscript test I can come up with:

```
#!/usr/bin/env kscript

@file:DependsOn("org.javamoney:moneta:1.3@pom")

import org.javamoney.moneta.Money

println("Money works! " + Money.of(9000, "EUR"))
```

I'd be happy to contribute. Maybe there is a good regex to allow both, classifier and type, as optional params.

**Comment by holgerbrandl** [comment] 2018-09-05 20:13
Exactly, we'd need to replace the simplistic split in https://github.com/holgerbrandl/kscript/blob/618759173e2f57d3d04c818435e527d1acfb3bda/src/main/kotlin/kscript/app/DependencyUtil.kt#L38 with some slightly more sophisticated regex and uupdate the pom generation accordingly.

You're more than welcome to provide a PR (including the example from above as unit test). I could also try to implement it, but it may take a week or two, since I'm rather busy momentarily to prepare my presentation for the upcoming KotlinConf in Amsterdam. Just let me know how you feel about it.

**Comment by andreas-mausch** [comment] 2018-09-05 20:26
Sure, I'll give it a try.

A friend of mine, Niels Falk, will be at the KotlinConf, too. If you meet him by chance say hello from me. :smile:

**Comment by andreas-mausch** [comment] 2018-09-06 00:04
Ok I made some progress, but now I've learned something new and tests are still red.

In kscript, you can access a class, but if you try to load it via the thread's classloader, it will fail:
```
@file:DependsOn("log4j:log4j:1.2.14")
org.apache.log4j.Logger.getRootLogger() // this is fine

val contextClassLoader = Thread.currentThread().getContextClassLoader()
contextClassLoader.loadClass("org.apache.log4j.Logger") // this crashes with ClassNotFoundException
```

moneta tries to do something similar in javax.money.spi.Bootstrap.loadDefaultServiceProvider():
ServiceLoader.load(ServiceProvider.class)

..and then you get a consequential error "Caused by: UnknownCurrencyException [currencyCode=EUR]".

This is a completely different issue, and I'd like to commit what I've done as I believe it is working, however my original test case is still failing.
I'll try to find a simpler library tomorrow which uses "@pom" and finish the test case with it.

And then I will create a new issue for the classloader thing. Or is it #109?

**Comment by holgerbrandl** [comment] 2018-09-06 09:51
Indeed #109 it is, but also #131.

Imho it's clearly a platform bug. The corresponding tickets are

* https://youtrack.jetbrains.net/issue/KT-26624 (just reported by me using your example)
* https://youtrack.jetbrains.net/issue/KT-24991

You could also vote for https://youtrack.jetbrains.net/issue/KT-24966 which centers around the same issue.

Sorry for inconvenience.

**Comment by holgerbrandl** [comment] 2018-09-06 09:53
When running your test it fails with 
```
kscript ${KSCRIPT_HOME}/test/resources/depends_on_with_type.kts
[kscript] Resolving dependencies...
[kscript] Downloading: http://jcenter.bintray.com/org/javamoney/moneta/1.3@pom/moneta-1.3@pom.pom
[kscript] Downloading: https://repo.maven.apache.org/maven2/org/javamoney/moneta/1.3@pom/moneta-1.3@pom.pom
[kscript] Downloading: http://jcenter.bintray.com/org/javamoney/moneta/1.3@pom/moneta-1.3@pom.jar
[kscript] Downloading: https://repo.maven.apache.org/maven2/org/javamoney/moneta/1.3@pom/moneta-1.3@pom.jar
Failed to lookup dependencies. Maven reported the following error:
[ERROR] Failed to execute goal on project maven_template: Could not resolve dependencies for project kscript:maven_template:jar:1.0: Could not find artifact org.javamoney:moneta:jar:1.3@pom in jcenter (http://jcenter.bintray.com/) -> [Help 1]
```
So it seems we can not resolve `org.javamoney:moneta:1.3@pom`. Is it part of a different maven repo? (which we could add via `@file:MavenRepository`)

**Comment by andreas-mausch** [comment] 2018-09-06 11:37
I see.

I've got an email that dependencies couldn't be resolved, but can't find the message here. Is it solved? If yes, let's close this issue! :trumpet: 
(Oh and sorry for breaking the styling, I accidentally commited the file after formatting.)

So if kscript gets integrated into kotlin (is this being discussed already?) and this classloader thing is solved I would prefer it all day long over python.

Thanks for creating the issue at jetbrains.
And thanks for answering so fast here. It's super fun like this.

**Comment by holgerbrandl** [comment] 2018-09-06 12:40
Sorry for the spam. My fault, I did not empty my cache before running the test, and silently removed my comment after realizing the problem. Bad practice, I now. ;-)

The question about integrating it was brought up by Hadi from from JB, but without any followup until now. I wouldn't mind, because it would free some time for other projects, I'd love to work on.

Thanks again for your contribution.

**Closed by holgerbrandl** 2018-09-06 12:40 UTC

**Comment by andreas-mausch** [comment] 2018-09-08 04:28
I found a (hacky) workaround for moneta:

```
#!/usr/bin/env kscript

@file:DependsOn("org.javamoney:moneta:1.3@pom")

import org.javamoney.moneta.Money

class XY {

}

println("classloader is of type:" + Thread.currentThread().contextClassLoader)
println("classloader is of type:" + ClassLoader.getSystemClassLoader())
println("classloader is of type:" + XY::class.java.classLoader)

Thread.currentThread().contextClassLoader = XY::class.java.classLoader

println("Money works! " + Money.of(9000, "EUR"))
```

```
classloader is of type:sun.misc.Launcher$AppClassLoader@33909752
classloader is of type:sun.misc.Launcher$AppClassLoader@33909752
classloader is of type:java.net.URLClassLoader@372f7a8d
Sep 08, 2018 6:25:04 AM org.javamoney.moneta.DefaultMonetaryContextFactory createMonetaryContextNonNullConfig
INFORMATION: Using custom MathContext: precision=256, roundingMode=HALF_EVEN
Money works! EUR 9000
```

**Comment by holgerbrandl** [comment] 2018-09-10 06:38
Great that you could get it to work. Though, flipping classloaders feels indeed like black jvm-magic to me. :-)
