### ISSUE TITLE
SLF4J provider does not load

### ISSUE THREAD

**Issue by NikkyAI** [holgerbrandl/kscript#167] opened 2018-09-14 09:55 UTC
a library i try to use via Maven dependency makes use of kotlin-logging, which in turn uses slf4j
when launching through kscript i am greeted with the following:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
```

i tried adding sljf4-simple and logback-classic as maven dependencies
this has no effect either

**Comment by oshai** [comment] 2018-09-14 10:32
I think your missing a binding dependency. See here:
http://saltnlight5.blogspot.com/2013/08/how-to-configure-slf4j-with-different.html?m=1

בתאריך יום ו׳, 14 בספט׳ 2018, 12:55, מאת NikkyAI ‏<notifications@github.com

**Comment by NikkyAI** [comment] 2018-09-14 13:12
just thiese 2 dependencies in gradle work just fine
```
    compile(group = "io.github.microutils", name = "kotlin-logging", version = "1.6.10")
    compile(group = "org.slf4j", name = "slf4j-simple", version = "1.8.0-beta2")
```

i think this is more a issue of log4j being unable to load the provider from classpath

**Comment by holgerbrandl** [comment] 2018-09-14 15:36
It could be the known kotlin classloader problem as described under https://github.com/holgerbrandl/kscript/issues/155#issuecomment-419034634

**Comment by NikkyAI** [comment] 2018-09-14 15:50
indeed the mentioned classloader swapping hack fixes it for me
hope to see a real solution though
since this is technically a duplicate should i close this issue ?

**Comment by holgerbrandl** [comment] 2018-09-18 06:16
Don't forget to vote on the youtrack issue. Duplicate of #155

**Closed by holgerbrandl** 2018-09-18 06:16 UTC
