### ISSUE TITLE
Integrate/use Capsule

### ISSUE THREAD

**Issue by fab1an** [holgerbrandl/kscript#90] opened 2018-01-10 12:41 UTC
There is capsule (http://www.capsule.io), which facilitates packaging java application in single jars. It also has automatic dependency downloads, caching, configuration for the JVM, it can launch auxiliary scripts etc.

It's pretty feature-complete: http://www.capsule.io/user-guide/

Just wanted to let you know so you don't have to develop functionality that's already there.

**Comment by holgerbrandl** [comment] 2018-01-11 09:30
Thanks for the very interesting pointer. Maybe this could be used to implement #63.

**Comment by fab1an** [comment] 2018-01-11 10:02
Certainly. Capsule can also check if required java versions are installed and display according messages.
Shipping a chopped up jdk should be possible with JDK9 if I'm not mistaken, I'm sure capsule's author will integrate that at some point.

**Comment by holgerbrandl** [comment] 2018-02-09 09:30
I'm closing the ticket as a duplicate of 63. I think I'll try to implement the packaging via the capsule-gradle-plugin, so thanks for the pointer.

**Closed by holgerbrandl** 2018-02-09 09:30 UTC
