### ISSUE TITLE
script --package 'println("whatever")' Type 'FatCapsule' property 'applicationSource' is missing an input or output annotation.

### ISSUE THREAD

**Issue by HoffiMuc** [holgerbrandl/kscript#317] opened 2021-05-14 13:27 UTC
any ideas? probably a version incompatibility but of _what_ ?

```
$ gradle --version

------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7)
OS:           Mac OS X 11.3.1 x86_64


$ kscript --package 'println("whatever")'
[kscript] Packaging script 'kscriptlet.590b37730cf8e0f5' into standalone executable...
[kscript] [ERROR] packaging of 'kscriptlet.590b37730cf8e0f5' failed:
            Exit Code   : 1Comand      : bash -c cd '/Users/hoffi/.kscript/kscript_tmp_project__scriptlet.590b37730cf8e0f5.jar_1620998675327' && gradle simpleCapsule
            Stdout      : > Task :compileKotlin NO-SOURCE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :simpleCapsule FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings
3 actionable tasks: 3 executed

            Stderr      :

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':simpleCapsule' (type 'FatCapsule').
  - Type 'FatCapsule' property 'applicationSource' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'FatCapsule' property 'capletConfiguration' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'FatCapsule' property 'capsuleConfiguration' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'FatCapsule' property 'capsuleFilter' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'FatCapsule' property 'capsuleManifest' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 570ms
```

**Comment by holgerbrandl** [comment] 2021-05-28 11:44
I've just tried with gradle 7.0.1 and it worked. I use java11 though, could you try with that version (just to narrow down the problem root cause)?

**Comment by eygraber** [comment] 2021-06-09 16:43
I tried with Gradle 7.0.2 and also got the error:

```
[kscript] [ERROR] packaging of 'my-script' failed:
            Exit Code   : 1Comand      : bash -c cd '/home/eli/.kscript/kscript_tmp_project__my-script.209e1524d0704e21.jar_1623256835415' && gradle simpleCapsule
            Stdout      : Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileKotlin NO-SOURCE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :simpleCapsule FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings
3 actionable tasks: 3 executed

            Stderr      : 
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':simpleCapsule' (type 'FatCapsule').
  - Type 'us.kirchmeier.capsule.task.FatCapsule' property 'applicationSource' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'us.kirchmeier.capsule.task.FatCapsule' property 'capletConfiguration' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'us.kirchmeier.capsule.task.FatCapsule' property 'capsuleConfiguration' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'us.kirchmeier.capsule.task.FatCapsule' property 'capsuleFilter' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'us.kirchmeier.capsule.task.FatCapsule' property 'capsuleManifest' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

```

**Comment by kenyee** [comment] 2021-06-18 15:24
Confirmed that Gradle 7.0.2 fails...thanks for logging this.  Was trying to figure out what changed in my environment.
Is there any way to tell it to use a specific version of Gradle?

**Comment by holgerbrandl** [comment] 2021-06-23 19:54
I'm a bit lost here. Could you suggest a fix? How could we adopt kscript to keep this feature in the loop?

**Comment by ScottPeterJohnson** [comment] 2021-08-01 02:53
I believe what's happening here is that Gradle 7 introduces a validation check on spec classes, requiring their properties be annotated to classify them as inputs/outputs/internal. Ultimately the problem is with the gradle-capsule-plugin, whose properties aren't annotated:

https://github.com/danthegoodman/gradle-capsule-plugin/blob/master/src/main/groovy/us/kirchmeier/capsule/task/Capsule.groovy

This would have to be fixed in that plugin- which unfortunately seems to have been dead for 5 years. (I'd fork it myself, but I don't know Groovy.) See [here](https://github.com/psxpaul/gradle-execfork-plugin/issues/36) for this issue in a different plugin.

**Comment by aartiPl** [comment] 2022-07-10 16:07
This issue is irrelevant now. In the development version of kscript (kscript_4.1 branch) there is a solution that doesn't use the Capsule plugin.

**Closed by aartiPl** 2022-07-10 16:07 UTC
