### ISSUE TITLE
Updating to 2.7 breaks dependency resolution

### ISSUE THREAD

**Issue by cjbrooks12** [holgerbrandl/kscript#220] opened 2019-03-20 23:54 UTC
It looks like the update to 2.7 (with the new dependency resolution mechanism) is not working. The example script [here](https://orchid.netlify.com/wiki/user-manual/getting-started/quickstart#kscript) worked just fine in 2.5, but in 2.7 I get some `java.lang.NoClassDefFoundError` errors.

Here's the full output:

```
[kscript] Resolving dependencies...
[kscript]     Resolving io.github.javaeden.orchid:OrchidAll:0.16.1...Done
[kscript]     Resolving com.github.holgerbrandl:kscript-annotations:1.2...Done
[kscript] Dependencies resolved
Using the following modules:
--------------------
 * com.eden.orchid.StandardModule

Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at Main_Start$Companion.main(Main_Start.kt:6)
    at Main_Start.main(Main_Start.kt)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
    at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
    at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
Caused by: java.lang.NoClassDefFoundError: com/vladsch/flexmark/ext/aside/AsideExtension
    at com.eden.orchid.impl.compilers.markdown.FlexmarkModule.configure(FlexmarkModule.kt:19)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
    at com.google.inject.AbstractModule.install(AbstractModule.java:103)
    at com.eden.orchid.api.registration.ClasspathModuleInstaller.lambda$configure$0(ClasspathModuleInstaller.java:28)
    at java.util.ArrayList.forEach(ArrayList.java:1257)
    at com.eden.orchid.api.registration.ClasspathModuleInstaller.configure(ClasspathModuleInstaller.java:23)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
    at com.google.inject.AbstractModule.install(AbstractModule.java:103)
    at com.eden.orchid.StandardModule.configure(StandardModule.kt:34)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
    at com.google.inject.spi.Elements.getElements(Elements.java:103)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
    at com.google.inject.Guice.createInjector(Guice.java:87)
    at com.google.inject.Guice.createInjector(Guice.java:69)
    at com.eden.orchid.Orchid.start(Orchid.java:83)
    at Start.<init>(start.kts:45)
    ... 13 more
Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.ext.aside.AsideExtension
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 33 more
```

This issue was initially discussed on the [Orchid Gitter chat](https://gitter.im/JavaEden/Orchid).

**Comment by holgerbrandl** [comment] 2019-03-27 20:59
@andreas-mausch do you think this could be related to our thinned out aether bundling? See https://github.com/holgerbrandl/kscript/blob/master/build.gradle.kts#L15

**Comment by andreas-mausch** [comment] 2019-03-28 09:02
Very likely :( ...I can check it on Monday evening

**Comment by holgerbrandl** [comment] 2019-04-04 07:05
Any news already @andreas-mausch ?

**Comment by andreas-mausch** [comment] 2019-04-04 09:28
Uh sorry, not yet. Won't be able to do it today, either, but hopefully tomorrow.

**Comment by andreas-mausch** [comment] 2019-04-04 13:28
@holgerbrandl I've tested 2.6.0 vs. a self-build 2.7.1.

After running 2.7.1 I can confirm I see the same error.

When executing the same script with 2.6.0, the error remains.
But once I clean my ~/.kscript directory, the script runs without errors.

So yea, as assumed it's on me. :( Sorry guys.

I try to fix it on Saturday.

Thanks @cjbrooks12 for the detailed info.

**Comment by andreas-mausch** [comment] 2019-04-04 13:29
Transitive dependencies are resolved correctly, but not added to the classpath.

[dependency_cache.2.6.0.txt](https://github.com/holgerbrandl/kscript/files/3043651/dependency_cache.2.6.0.txt)
[dependency_cache.2.7.1.txt](https://github.com/holgerbrandl/kscript/files/3043652/dependency_cache.2.7.1.txt)

**Comment by andreas-mausch** [comment] 2019-04-04 14:04
@holgerbrandl Not even transitive dependencies are the problem, but I've specified the wrong scope.

Changing COMPILE to RUNTIME solves the problem for me: https://github.com/holgerbrandl/kscript/blob/8bf4a6d91c4f584cb0403653fb26fa1937b3324c/src/main/kotlin/kscript/app/DependencyUtil.kt#L77

```
[neonew@neonew-xps15 kscript]$ kscript --clear-cache
Cleaning up cache...
[neonew@neonew-xps15 kscript]$ ${KSCRIPT_HOME}/test/test_suite.sh
...................
all 19 script_input_modes tests passed in 66.263s.
...
all 3 environment_tests tests passed in 7.593s.
......
all 6 dependency_lookup tests passed in 11.250s.
......
all 6 annotation_config tests passed in 31.034s.
.....
all 5 support_api tests passed in 14.012s.
...........
all 11 custom_interpreters tests passed in 95.738s.
..........
all 10 misc tests passed in 28.437s.
.
all 1 junit_tests tests passed in 2.978s.
.....
all 5 bootstrap_header tests passed in 9.578s.
```

Should I create a PR or do you prefer to change it directly?

**Comment by holgerbrandl** [comment] 2019-04-09 06:38
Great that you could find it. I'll try to fix it myself. Thanks for your help.

**Comment by kevcodez** [comment] 2019-05-29 10:05
Is this getting fixed? 2.7.1 is unusable due to dependencies not being resolved. Downgrading to 2.6.0 is my workaround for now.

**Comment by holgerbrandl** [comment] 2019-06-07 14:05
I think it's solely an issue with the build and not with the changes. I've just tested a fresh working copy on a linux and the current master (which is essentially just v2.7.1) and it seems fine.

**Comment by jobnz** [comment] 2019-06-14 19:47
I'm building kscript (current master) on linux (Archlinux) as well and i still experience the problem described above. A clean build does not work for me.

**Comment by holgerbrandl** [comment] 2019-06-17 06:11
Hmm, that's strange,  both travis ci and running the build+tests locally under linux is fine for me.

What is the error? Is it build or test-related?

**Comment by jobnz** [comment] 2019-06-17 17:52
Both assembling and testing finish without errors. Running a script with dependencies yields the following error:

`[kscript] Resolving dependencies...
[kscript]     Resolving com.xenomachina:kotlin-argparser:2.0.7...Exception in thread "main" java.lang.NoClassDefFoundError: org/ietf/jgss/GSSException
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.<clinit>(NettyAsyncHttpProvider.java:177)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector.getDefaultProvider(AsyncRepositoryConnector.java:246)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector.getProvider(AsyncRepositoryConnector.java:241)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector.<init>(AsyncRepositoryConnector.java:154)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnectorFactory.newInstance(AsyncRepositoryConnectorFactory.java:106)
	at org.sonatype.aether.impl.internal.DefaultRemoteRepositoryManager.getRepositoryConnector(DefaultRemoteRepositoryManager.java:346)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:281)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:186)
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:191)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:333)
	at com.jcabi.aether.Aether.fetch(Aether.java:228)
	at com.jcabi.aether.Aether.resolve_aroundBody2(Aether.java:180)
	at com.jcabi.aether.Aether$AjcClosure3.run(Aether.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.aether.Aether.resolve(Aether.java:177)
	at com.jcabi.aether.Aether.resolve_aroundBody0(Aether.java:163)
	at com.jcabi.aether.Aether$AjcClosure1.run(Aether.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.aether.Aether.resolve(Aether.java:156)
	at kscript.app.DependencyUtilKt.resolveDependenciesViaAether(DependencyUtil.kt:78)
	at kscript.app.DependencyUtilKt.resolveDependencies(DependencyUtil.kt:52)
	at kscript.app.KscriptKt.main(Kscript.kt:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
Caused by: java.lang.ClassNotFoundException: org.ietf.jgss.GSSException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 38 more
`

I'm actually not sure if it is the same error but it looks much alike.

**Comment by andreas-mausch** [comment] 2019-06-17 20:27
@jobnz 
Did you try to use "--clear-cache"?

If you can provide the script I'd take a look.

**Comment by holgerbrandl** [comment] 2019-06-18 07:26
Could also be a java module problem (see #163) or a kotlin issue when it comes to reflection (see #131 and the linked platform issue https://youtrack.jetbrains.net/issue/KT-24966). 

However, in general, I agree with Andreas that providing an example would be very helpful to dig into the issue.

**Comment by jobnz** [comment] 2019-06-18 07:32
I attached the script file: [set-config.txt](https://github.com/holgerbrandl/kscript/files/3300287/set-config.txt). @andreas-mausch sorry, i don't with which tool i should try to use "--clear-cache"

**Comment by holgerbrandl** [comment] 2019-06-18 07:39
Take a wild guess! :-) ... `kscript --clear-cache` will wipe its internal compile and dependency resolver cache.

Thanks for providing the example. It works for me:
```
brandl@ocker01:~$ kscript ./set-config.kts set-config
missing DEST operand
```
So I'd also think that its rather a cache or an environment problem. What is your version of java?

**Comment by jobnz** [comment] 2019-06-18 07:49
I'm using java 10.0.2 and i didn't expect the kscript cache to be the problem since i never used kscript before. I installed only for run the script i provided

**Comment by jobnz** [comment] 2019-06-18 07:59
I changed the java version in use and i turns out it works with java 8 but not with java 10. Thank you for your help and pointing me to the other issues!

**Comment by holgerbrandl** [comment] 2019-06-18 08:15
So it's most certainly module system related.

Please vote on https://youtrack.jetbrains.com/issue/KT-28475 and check out #163 

@andreas-mausch I still wonder if the required modules could be provided as an argument to @file:KotlinOpts in some way? If it could be done via `java` CLI it should be forwarded by `kotlin` I guess  when using `-J<option>`

**Comment by holgerbrandl** [comment] 2019-06-18 08:15
@jobnz  The command to clear the cache would be `kscript --clear-cache` which is supposed to be run in a bash shell.

**Comment by jobnz** [comment] 2019-06-18 08:18
@holgerbrandl I know. I meant that i ran `kscript --clear-cache` but the error describe earlier remained.

**Comment by andreas-mausch** [comment] 2019-06-18 08:26
> @andreas-mausch I still wonder if the required modules could be provided as an argument to @file:KotlinOpts in some way? If it could be done via `java` CLI it should be forwarded by `kotlin` I guess when using `-J<option>`

Are you referring to the `--add-modules java.sql` argument? Yes, that sounds very reasonable.

Regarding this issue: I think it's fixed, right? As @jobnz issue is related to the Java version.

**Comment by holgerbrandl** [comment] 2019-06-21 20:51
Yep, seems fixed to me as well

**Closed by holgerbrandl** 2019-06-21 20:51 UTC
Labels: bug
