### ISSUE TITLE
Remove need to supply OsType

### ISSUE THREAD

**Issue by jayvdb** [holgerbrandl/kscript#362] opened 2022-06-04 12:21 UTC
v4.0.3 really helped getting kscript working on various platforms.
However, it required that the first arg was one of the OsTypes at https://github.com/holgerbrandl/kscript/blob/master/src/main/kotlin/kscript/app/model/OsType.kt#L4

This broken the ability to use kscript using `kotlin -classpath /path/to/kscript.jar kscript.app.KscriptKt filename` and `java -jar /path/to/kscript.jar filename`.

It is a bit odd that we need to provide the os name as the first arg.  Most formatters/linters/etc only require a filename arg.
It should be able to detect this using `getProperty("os.name")`, with perhaps an override with a cli option like `--os=cygwin` if it is some weird platform which `os.name` doesn't accurately describe.

**Comment by aartiPl** [comment] 2022-06-04 19:01
Unfortunately, it is impossible to correctly detect OsType by just using `getProperty("os.name")`. On both Cygwin and MSys 'os.name' is reported as "Windows 10", which does not contain real information about shell which was used to invoke kscript.

In the long term I think that kscript should be aware of the shell on which it is running, and maybe even pass this piece of information to scripts that it executes. So from that point of view, I would say it is the best way to pass most correct system information.

Can you please elaborate why in your use case the change should prohibit anyone from starting compiled script manually? It should be easy enough to just pass additional argument e.g. "linux", and everything should work as before.

**Comment by jayvdb** [comment] 2022-06-05 12:43
On Windows, when run from within another program, a `.bat` file doesnt cut it.  `.bat` only works in the command prompt.  I am using Python and it can not run `.bat` files.

So I need to use the .jar directly.  And the JAR CLI interface just broke by the addition of an unnecessary argument being added.  So now I need to construct an OsType based on the platform that my program is running on, usually windows/linux/darwin.

I realise that "os.name" doesn't always precisely identify the platform, hence I mentioned an override to help for cygwin/msys/etc.

**Comment by aartiPl** [comment] 2022-06-05 13:29
You can execute kscript jar and provide OSType as a parameter:
`kotlin -classpath /path/to/kscript.jar kscript.app.KscriptKt linux`

That way it will work as before. I would additionally encapsulate it in some Python function, so that you don't have to bother every time with passing an additional argument to kscript. Maybe you can even create kscript.py and we can put it as another wrapper for kscript for python console users if it helps to resolve this issue.

Your use case seems somewhat special. And still, there are simple workarounds to make it work again. Most users will require to have correct, cross-platform compatibility and it will be difficult to achieve that without knowing the exact Os type where kscript was run.

**Comment by aartiPl** [comment] 2022-06-08 15:34
I am closing this issue now. Anyway, it will be highly appreciated if you can provide PR for the Python wrapper.

**Closed by aartiPl** 2022-06-08 15:34 UTC

**Comment by vsajip** [comment] 2022-06-21 21:11
> You can execute kscript jar and provide OSType as a parameter - `kotlin -classpath /path/to/kscript.jar kscript.app.KscriptKt linux`

Well, of course this will only _print_ the command that needs to be run, since `kscript` currently relies on Bash or a `.bat` file using `FOR /F` to effectively execute that printed command - the code in `kscript.jar` doesn't actually run the script code itself. So a Python script would need to run `subprocess` code to spawn a process to execute that printed command.

@aartiPl I take it there are no plans to change `kscript.jar` to actually _run_ the command rather than just print it?

**Comment by aartiPl** [comment] 2022-06-22 05:53
There are no plans, but only because of the fact that currently, I concentrate more on having multi-OS support. But it would make sense in my opinion, and maybe even will make multi-OS support easier. But before the switch, we would have to understand better why kscript was designed in such a way and check if the change does not break some of its usage scenarios.
