### ISSUE TITLE
the released 4.0.0 version can not download dependency from maven repo, back to 3.1.0 runs ok 

### ISSUE THREAD

**Issue by Nvsleep** [holgerbrandl/kscript#345] opened 2022-04-28 08:40 UTC
[kscript] Resolving wu.seal:kscript-tool:1.0.13...
[kscript] Resolving com.google.code.gson:gson:2.8.9...
[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscriptFile 'wu.seal:kscript-tool:1.0.13' not found
[kscript] [ERROR] org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for wu.seal:kscript-tool:jar:1.0.13
[kscript] [ERROR] org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for wu.seal:kscript-tool:jar:1.0.13

**Comment by holgerbrandl** [comment] 2022-04-28 11:28
Sorry for the inconvenience. Could you share an example to reproduce the problem?

**Comment by marcouberti** [comment] 2022-04-28 16:13
The same is happening on my CI starting from today:

```
[kscript] Resolving com.squareup.okhttp3:okhttp:4.9.3...
[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscriptFile 'com.squareup.okhttp3:okhttp:4.9.3' not found
[kscript] [ERROR] org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for com.squareup.okhttp3:okhttp:jar:4.9.3
[kscript] [ERROR] org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for com.squareup.okhttp3:okhttp:jar:4.9.3
```

**Comment by aartiPl** [comment] 2022-04-28 16:41
As far as I can say it is a problem with a Kotlin Scripting artifact resolver: whenever the artifact is in the local artifacts cache it works correctly, but for remote resolution, it doesn't work. 

This resolver was working correctly in Kotlin 1.4, but after upgrading to the latest version of Kotlin it has started to fail. During my tests of the kscript4 branch, I was able to make it work by using the most dependencies for Kotlin at version 1.5, but only keeping kotling-scripting dependency at version 1.4.

Here is the ticket at JetBrains:
https://youtrack.jetbrains.com/issue/KT-50069

The above ticket did not get much traction, most probably because no one else has reported that problem. It would be great if someone can repeat my tests by changing the version of Kotlin dependencies and once again analyze the KScript dependency resolution code. The new dependency resolution code in KScript is in fact very similar to the previous KScript version resolver, so seems like updating KScript dependency to the new kotlin-scripting artifact version broke KScript.

**Comment by cybo42** [comment] 2022-04-28 16:42
I noticed same issue below are snippets from my kscript:

```
#!/usr/bin/env kscript
import DependsOn
import kotlin.system.exitProcess

@file:Include("../utils/secrets/build/generated/source/nytsecrets/release/com/nytimes/android/secrets/Secrets.kt")
@file:Include("base.kt")
@file:DependsOn("com.offbytwo:docopt:0.6.0.20150202")

import org.docopt.Docopt
```

On new instance using kscript 4.0.0 I get the below error:
```
[kscript] Resolving com.offbytwo:docopt:0.6.0.20150202...
[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscriptFile 'com.offbytwo:docopt:0.6.0.20150202' not found
[kscript] [ERROR] org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for com.offbytwo:docopt:jar:0.6.0.20150202
[kscript] [ERROR] org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for com.offbytwo:docopt:jar:0.6.0.20150202
```

Under 3.1.0 on new instance
```
[kscript] Detected missing dependencies in cache.
[kscript] Resolving dependencies...
[kscript] Resolving com.offbytwo:docopt:0.6.0.20150202...
[kscript] Resolving com.github.holgerbrandl:kscript-annotations:1.4...
[kscript] Dependencies resolved
```

If the dependency is already present in `.m2/repository` on the instance then it appears to resolve without issue

**Comment by aartiPl** [comment] 2022-04-28 16:45
If you can do the additional tests and confirm my hypothesis - we can upvote Jetbrains ticket. Please see my comment: https://github.com/holgerbrandl/kscript/issues/345#issuecomment-1112428775

**Comment by holgerbrandl** [comment] 2022-04-28 17:02
I guess we then need to roll back the scripting dependencies to the version initially suggested by @aartiPl . I was hoping that the problem would have been resolved upstream.


@aartiPl We should also add some tests that intentionally prune some subtree of the local .m2 cache to ensure that the resolver is tested correctly.  With the cached .m2 copies of the dependencies I completly missed this major regression.

**Comment by holgerbrandl** [comment] 2022-04-28 19:51
I've added more tests and I struggle to reproduce the problem. Here's a basic protocol

```
brandl@ubuntu:kscript$ rm -rf .m2/repository/log4j/log4j/1.2.14/; kscript --clear-cache
Cleaning up cache...
brandl@ubuntu:kscript$ kscript --version
kscript - Enhanced scripting support for Kotlin on *nix-based systems.

Usage:
 kscript [options] <script> [<script_args>]...
 kscript --clear-cache

The <script> can be a script file (*kts), a script URL, - for stdin, a *.kt source file with a main method, or some kotlin code.

Use '--clear-cache' to wipe cached script jars and urls

Options:
 -i --interactive        Create interactive shell with dependencies as declared in script
 -t --text               Enable stdin support API for more streamlined text processing
 --idea                  Open script in temporary Intellij session
 -s --silent             Suppress status logging
 -d --development        Enable logging of exception stack trace and additional log messages
 --package               Package script and dependencies into self-dependent binary
 --add-bootstrap-header  Prepend bash header that installs kscript if necessary


Copyright : 2021 Holger Brandl
License   : MIT
Version   : v4.0.0
Website   : https://github.com/holgerbrandl/kscript
Kotlin    : 1.6.21-release-334
Java      : JRE 11.0.15+10
brandl@ubuntu:kscript$ cat ticket_345.kts 
#!/usr/bin/env kscript

@file:DependsOn("log4j:log4j:1.2.14", "com.offbytwo:docopt:0.6.0.20150202")

//import DependsOn
import kotlin.system.exitProcess


import org.docopt.Docopt

org.apache.log4j.Logger.getRootLogger()
brandl@ubuntu:kscript$ kscript ticket_345.kts 
[kscript] Resolving log4j:log4j:1.2.14...
[kscript] Resolving com.offbytwo:docopt:0.6.0.20150202...
brandl@ubuntu:kscript$ 
```

So at least the resolver part seems fine. Could you help me to reproduce this issue?

**Comment by aartiPl** [comment] 2022-04-30 17:28
There is test case in main repository for this issue: "IntegrationTest345.main.kts". It fails for me every time, even before resolving "com.beust:klaxon:5.5". Below the screenshot from session with enabled development mode "-d".

kscript -d IntegrationTest345.main.kts

![obraz](https://user-images.githubusercontent.com/1508798/166008114-4afde70f-7c8f-432c-9b5c-fd3d5c4c0a77.png)

As you can see it throws from "org.eclipse.aether.resolution.DependencyResolutionException" (DependencyResolver.kt:51).

Does anyone know how to access Aether source code? The project is already archived in Eclipse, and I couldn't find any trace of its source code.

**Comment by holgerbrandl** [comment] 2022-05-02 06:20
I had added this test (which should be moved to tests later I think) to assess if the resolver would generally work when bypassing kscript (which seems to be the case).

Since aether is coming in as a transitive dependency, I do not know where the sources are maintained now. It was indeed archived away a while ago.

**Comment by aartiPl** [comment] 2022-05-03 11:47
I have a few new findings in regards to this issue:

1. 'aether' project is deprecated, but the direct successor of this library is 'maven-resolver' project (it even keeps the package naming); Link: https://github.com/apache/maven-resolver
2. 'kotlin-scripting-dependencies-maven' imports old 'aether' artifacts instead of 'maven-resolver' artifacts (**it should be fixed in 'kotlin-scripting-dependencies-maven' as 'maven-resolver' artifacts are also imported as a dependency**)
3. I have added IntegrationTest345 also to the test directory in kscript; I have implemented 'fun main()' there and I have started it by using that function. That way IntegrationTest345 has passed, while when started using kscript it fails.

Because of that, I suspect that there are differences in classpath between IntelliJ (where resolver works) and Kscript. Cannot pinpoint specific dependencies though.

**Comment by holgerbrandl** [comment] 2022-05-03 12:17
In the past the classloader in the kotlin binary worked differently compared to the java classloader (which is also used in the IDE). Maybe this points to the root cause?

@ligee Is (2) Intentionally or a bug?

**Comment by ileasile** [comment] 2022-05-03 22:51
`DependencyResolutionException` usually has a cause. Is it possible for you to look at the full chain of causes in debugger?

**Comment by ligee** [comment] 2022-05-04 05:57
@holgerbrandl, seems like a bug on our side, @ileasile is taking care about it.

**Comment by aartiPl** [comment] 2022-05-04 10:50
@ligee , @ileasile - How can we test changes? Can you create temporary artifacts e.g. SNAPSHOT, so that I can apply in kscript and recheck?

**Comment by ileasile** [comment] 2022-05-04 10:54
@aartiPl https://youtrack.jetbrains.com/issue/KT-50069/Maven-artefacts-resolving-doesn-t-work#focus=Comments-27-6053576.0-0

**Comment by ileasile** [comment] 2022-05-05 18:44
We kinda found out a reason and fixed the issue. Debugging helped me a lot. Just in case, I'll share how I've done it.
There is a `bin/kotlinc` file in kotlin compiler distribution. It's a shell script, and there is a place where JAVA_OPTS are set up. Add this argument there:
```
-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5006
```
(or you may just export JAVA_OPTS env variable with this value)

Then, setup Remote JVM debug configuration in IDEA:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/20319593/166999000-b3db87ef-ae10-46de-9c62-9e6e1919bbdb.png">

Then run your kscript command, like `kscript script.kts`. Execution should suspend. Setup breakpoints in kscript code. And finally run remote debug configuration. Execution should stop on breakpoint.

**Comment by aartiPl** [comment] 2022-05-05 18:59
/\ 
 |   Good stuff!
 
Thanks for helping with this issue!

**Comment by holgerbrandl** [comment] 2022-05-05 20:37
So cool, thanks a ton to both of you @ileasile  and @aartiPl for this great analysis and fix.

So @aartiPl, shall we apply your PR for a hotfix release and then wait until the fixed version of kotlin has been released before reollin it back to its current state?

**Comment by aartiPl** [comment] 2022-05-06 06:31
I need some more time to do additional testing and cleanup of the branch with fixes (I hope it will be ready at the latest on Saturday afternoon). 

We will not have to wait for a new version of Kotlin. The problem was with the incorrect merging of resources by Gradle shadow plugin. We can either change 'kotlin-scripting-dependencies-maven' artifact to 'kotlin-scripting-dependencies-maven-all' (preferred) or add an additional transformation step during the shadow jar building.

It seems that this change works correctly also with Kotlin 1.6.21, so I will use this version of Kotlin.

**Comment by ileasile** [comment] 2022-05-06 11:09
BTW, I was not able to execute the reproducer script even after the fix. It successfully resolves dependencies and compiles but fails on execution with different exceptions

**Comment by aartiPl** [comment] 2022-05-07 11:25
@ileasile - yes that's a bit strange, but taking into consideration that tests are passing without problems and in Kotlin 1.6.21 not every problem is fixed (still a dependency on aether artifacts) I would leave it for further testing in real-life conditions. There is huge improvement anyway. I have applied both solutions to make sure that the problem won't break kscript in any way.

@holgerbrandl - I think we can release a fixed version and see if there is an improvement.

**Comment by aartiPl** [comment] 2022-05-18 19:25
@here - there is a new version of kscript available: 4.0.2 - please retest with the new version.

**Comment by jschneider** [comment] 2022-05-19 09:17
4.0.2 solves the issue for me. Thanks!

**Comment by aartiPl** [comment] 2022-05-20 18:34
Seems to be solved now. If anyone still experiences problems with resolving artifacts, please reopen this ticket.

**Closed by aartiPl** 2022-05-20 18:34 UTC
Labels: bug
