### ISSUE TITLE
`--package` not working with Gradle 5.0

### ISSUE THREAD

**Issue by abelsromero** [holgerbrandl/kscript#197] opened 2018-12-01 20:09 UTC
Running the package option with gradle 5.0 installed causes it to fail with the underlying gradle message.
```
Gradle does not allow passing null for the configuration action for CopySpec.from()
```
Note that the message was captured debugging.

With gradle 4.10.2, it worked fine.

**Comment by abelsromero** [comment] 2018-12-01 21:11
Seems to be a known issue with no quick solution https://github.com/danthegoodman/gradle-capsule-plugin/issues/38

**Comment by holgerbrandl** [comment] 2018-12-04 09:58
Thanks @abelsromero  for the pointer. So let's hope that they fix it soon. Not sure what to do about it on the kscript side.

**Comment by abelsromero** [comment] 2018-12-04 17:00
> Not sure what to do about it on the kscript side.

To keep current implementation we could "reverse engineer" the  gradle plugin and directly use the capsule API.
Or just build it the package in another way, I guess that so long as we add a bootstrap script to the path and have the jars somewhere we keep the feature the same from a user stand point. It would be nice also because that way we remove the dependency from gradle.

**Comment by holgerbrandl** [comment] 2018-12-06 22:09
I think the best approach would be to figure out and implement a PR for the `gradle-capsule-plugin` which fixes the problem.

**Comment by f-meloni** [comment] 2018-12-11 17:00
Apparently there is already a PR for that
https://github.com/danthegoodman/gradle-capsule-plugin/pull/39
But the problem is no longer really maintained, then could be worth evaluate remove it as dependency to avoid this kind of problems in the future.

**Comment by holgerbrandl** [comment] 2018-12-12 09:04
danthegoodman/gradle-capsule-plugin#39 seems to work only with gradle 5 and not with older gradles, otherwise I'd just fork the PR and push it to jcenter as a quickfix. But this option does not seems on the table, because at least gradle 4 should be supported by the plugin.

For sure the best solution would be to implement packaging in-process without calling an external tool. This would also remove the dependency on the capsule-gradle-plugin. Maybe capsule could be called programmatically? I would be very thankful for any help on such a feature. 

Alternatively with the new bootstrap header support contributed with #199 we could also think about dropping `--packaging` entirely? IMHO both are a bit too different, so it may be nice to maintain both packaging modes separately.

**Comment by gianluz** [comment] 2019-01-08 20:54
we have 2 new PRs https://github.com/danthegoodman/gradle-capsule-plugin/pull/41
and https://github.com/danthegoodman/gradle-capsule-plugin/pull/40

**Comment by holgerbrandl** [comment] 2019-01-12 22:17
@gianluz Is there a new version of the gradle-capsule-plugin with these PRs merged in already which we could use instead to fix this kscript packaging?

**Comment by gianluz** [comment] 2019-01-23 17:00
i forked gradle-capsule and opened this PR https://github.com/gianluz/gradle-capsule-plugin/pull/1

**Comment by gianluz** [comment] 2019-01-23 17:03
do you want to use this fork?

**Comment by holgerbrandl** [comment] 2019-01-23 21:59
As soon as it's published as corrected artifact on jcenter (or similar) yes.

**Comment by gianluz** [comment] 2019-02-02 21:04
I have published the new plugin, i'm just awaiting for approval, after that i'll open a PR here to fix the problem 😄

**Comment by f-meloni** [comment] 2019-02-06 15:06
@holgerbrandl Given https://github.com/holgerbrandl/kscript/pull/210 was merged, if you can please make a release I can check if the problem is solved :) 🎉 🚀

**Comment by aartiPl** [comment] 2022-07-09 23:31
There is a replacement of the capsule plugin in branch kscript_4.1. I am closing this ticket.

**Closed by aartiPl** 2022-07-09 23:31 UTC
Labels: bug, help wanted
