### ISSUE TITLE
Windows support with scoop installer without bash

### ISSUE THREAD

**Issue by raisercostin** [holgerbrandl/kscript#198] opened 2018-12-02 12:43 UTC
I tried to use this from windows. Unfortunately it needs a bash environment. I know that this is the intended purpose for this project.

I created a simple scoop installer but with a jar created from https://github.com/hj-lee/kscript (thanks @hj-lee ).

```
scoop add bucket raisercostin https://github.com/raisercostin/raiser-scoop-bucket
scoop install kscript

```

After that I was able to execute scripts with dependencies from windows without any bash help via a simple `kscript hello.ks`.

How can I help to have an official release with the merge from @hj-lee fork?

**Comment by hj-lee** [comment] 2018-12-04 21:52
Actually, my PR improves platform independence a bit as it makes kscript less dependant on bash.
By default, the main script uses the kscript java process, and if it uses runtime flags(such as -Xmx), it executes Java using Java process API on Windows instead of depending on bash.

**Comment by hj-lee** [comment] 2018-12-04 23:04
Regarding PR #194, it seems @abelsromero wants to use kscript on "git-bash". It is possible that PR #194 is not helpful to build scoop distribution. Also, I think my PR can be helpful to simplify PR #194 as my PR eliminates critical bash or cmd calls (compiling and executing). (Actually, my forked master branch has other changes, and one of them is "git-bash" support.)

**Comment by abelsromero** [comment] 2018-12-05 09:36
> Regarding PR #194, it seems @abelsromero wants to use kscript on "git-bash".

Just for testing because there's already a test suite written in bash. I have added more unit test, but I don't know enough he code to do more changes. In the long term I'd like to cover everything with Kotlin unit tests but that will require some refactor that I feel it's risky for my first PR.
If you see the code, you'll see that I have implemented native Windows calls:
* https://github.com/abelsromero/kscript/blob/add_windows_support/src/main/kotlin/kscript/app/AppHelpers.kt#L37
* https://github.com/abelsromero/kscript/blob/add_windows_support/src/main/kotlin/kscript/app/AppHelpers.kt#L111
* https://github.com/abelsromero/kscript/blob/add_windows_support/src/main/kotlin/kscript/app/AppHelpers.kt#L145

**Comment by abelsromero** [comment] 2018-12-05 10:00
> script-packaging will just work in bash.

That can be fixed and I'd recommend moving that conversation to https://github.com/holgerbrandl/kscript/issues/197. If we all agree that next release's goal is full Windows compatibility we just need some coordination 👍 

About @hj-lee I'd really like to see some of its improvements (specially the one "calling directly the kotlin compiler instead of bash") but I don't like "use classloader to run the script main and more" (I've experienced classpath pollution in gradle plugins that add code to the classpath).
Said that, I have to say that some of @hj-lee ideas are great but having many improvements in the same branch puts the leader in a complicated position of "all or nothing". How about splitting them so we can choose with ones we want merge asap?

**Comment by hj-lee** [comment] 2018-12-05 12:06
@abelsromero, #194 may be sufficient to support scoop, then. I guess @raisercostin can see?
Regarding #102, let's continue discussion on it.

(By the way, you're welcome @raisercostin)

**Comment by holgerbrandl** [comment] 2018-12-07 00:12
thanks @hj-lee and @abelsromero for your continued efforts to improve `kscript`.  I've read both PRs again, and here are my thoughts - side by side to easy the discussion.

Sorry @raisercostin for hijacking your ticket with this more general discusssion. :-)

## 194

pros

* preserves current execution model
* actual core or PR is slim: _just_ adds some quoting and path-tweaks along with `which`->`where` for improved windows compatiblity

cons

* PR adds includes many other changes. Some are arguage
	* possible incorrect way to guess KOTLIN_HOME under windows
	* new include resolve mechanism without clear reason* `KscriptTest.kt`m

* unclear if integration tests should not better be implemented for the shell, since kscript is a shell tool instead of jUnit. (imho they should go into the shell) 
* testing it on windows seems suboptimal. we should be able to run existing test_suite.sh in WSL and git-bash and have a dedicated suite for powershell.
* the kscript launcher is still highly unlikely to run under powershell. What did we gain? (WSL compatiblity? git-bash compatbility?) Can kscript work in powershell at all (without a new launcher)?



## 102

pros

* avoiding external tools where possible
* support for -J and -D makes sense
* calling java instead of kotlin may help to solve class loader issues which are known for kotlin scripting mode.(although it feels a bit like cheating on the platform :-)
* execellent prep for @ligee migration to new kotlin scripting API


cons

* incosistent execution model in presence/absence of `KOTLIN_OPTS`: 
	* first its using spawning a subprocess and 
	* second when doing so it using differing interpreters (java->kotlin). 
* unclear/potential classpath polution. Will the user code _inherit_ all the kscript dependencies? It must not imho to avoid version conflicts for instance.
* i was happy to have moved all `args` processing away from shell launcher, now it's coming back



## Other notes 

in presence of `KOTLIN_OPTS` there is no speed-improvment in #102 I think.

---
 `selfUpdate` should be removed (to specific and to tied to bash). users willwant to update using their preferred method anyway.

---

> Use java instead of kotlin - Call java instead of kotlin by building a fat kscript jar. 

@hj-lee how does the first part before the dash relate to other second part? I dont' see how your PR would build a fat jar, and I also don't think it's a good strategy because it would make initial script run very slow in case of complex dependencies.

---
> having many improvements in the same branch

Clearly smaller PRs are easier to merge. However its a bit tedious to create multiple PRs for every miniscule change, because they need to go into separate branches of the fork. So pooling them into a big-mother-of-all-PRs makes life much easier. :-)

Both #102 and #194 seem to stray from their original indent to some extent, but I can indeed cherry pick changes instead of a full merge as needed. So no need to split anything up.

## Summary

To me #194 is a more incremental workaround for an improved windows compatbility which comes with some unclear/uneeded other changes (listed above). I may exclude these from the merge, which I'll try to do in the next days. But even with the PR,  windows compatbility of kscript seems imho not really ready for primetime (missing powershell lancher, missing CI like using appveyor). 

Clearly #102 goes much deeper by changing the execution model. This definitly results in a cleaner design without so many external tool invocations. However, because I care about backwards compatiblity much more than about a slightly faster execution, I don't feel ready yet to merge it because of my concerns/questions listed above). Once these are resolved, #102 is clearly the way forward.

**Comment by abelsromero** [comment] 2018-12-08 19:09
> PR adds includes many other changes. Some are arguage
> 
>     * possible incorrect way to guess KOTLIN_HOME under windows

I tested several way and found no other that worked fine con cmd. :%

>     * new include resolve mechanism without clear reason* `KscriptTest.kt`m

I don't know what do you mean, I created the tests to help me test & and specially debug. They are not perfect, but the tests are the problem, feel free to delete them.
The dependency resolution is the result of the rebase from the master with https://github.com/holgerbrandl/kscript/pull/159.



>     * testing it on windows seems suboptimal. we should be able to run existing test_suite.sh in WSL and git-bash and have a dedicated suite for powershell.

I understood that was OK to be added in a separate PR.


>     * the kscript launcher is still highly unlikely to run under powershell. What did we gain? (WSL compatiblity? git-bash compatbility?) Can kscript work in powershell at all (without a new launcher)?

We can add a ".bat" similar to how gradlew works. Do you think this will suffice?

**Comment by holgerbrandl** [comment] 2018-12-10 12:55
> I don't know what you mean [about resolve mechanism]

Sorry for the confusion. I meant the change https://github.com/holgerbrandl/kscript/commit/e4c34d60b068d3f25b656e4eaa0f4fbbf576b14b#diff-71918461924a453d7a1654dcc529ba78R39

It may be a sound improvement, but the intent is not really clear to me yet.

> testing in separate PR. 

You already added some new tests, so my question/comment was rather about why the current tests are not sufficient to cover windows (e.g. when using `kscript` in a git-bash environment). I was initially under the impression that we wanted to fix `kscript` to pass the existing tests on windows first, and add more CI for git-bash, powershell, etc. later.

> We can add a ".bat" similar to how gradlew works. 

I have worked too little with windows in the last years, I don't know what the best practice would be. Providing a `*bat` version seems like a solution, but since `kscript` was intended to be used mainly as an interpreter (via shebang), so I'm not sure if `kscript.bat` would work.

**Comment by holgerbrandl** [comment] 2018-12-10 12:55
> I don't know what you mean [about resolve mechanism]

Sorry for the confusion. I meant the change https://github.com/holgerbrandl/kscript/commit/e4c34d60b068d3f25b656e4eaa0f4fbbf576b14b#diff-71918461924a453d7a1654dcc529ba78R39

It may be a sound improvement, but the intent is not really clear to me yet.

> testing in separate PR. 

You already added some new tests, so my question/comment was rather about why the current tests are not sufficient to cover windows (e.g. when using `kscript` in a git-bash environment). I was initially under the impression that we wanted to fix `kscript` to pass the existing tests on windows first, and add more CI for git-bash, powershell, etc. later.

> We can add a ".bat" similar to how gradlew works. 

I have worked too little with windows in the last years, I don't know what the best practice would be. Providing a `*bat` version seems like a solution, but since `kscript` was intended to be used mainly as an interpreter (via shebang), so I'm not sure if `kscript.bat` would work.

**Comment by abelsromero** [comment] 2018-12-15 17:20
Can't recall exactly why I did this in e4c34d6#diff-71918461924a453d7a1654dcc529ba78R39 other than the fact that "./" does not wok for a windows path with "\", and that this solution works fine for all OSs.

> Providing a `*bat` version

That's the standard approach, just check how gradle wrapper does.


BTW: I have to attend some thing following weeks :% so I think is better to close all other PRs first. After that I will create a new one from master including the changes and comments manually to avoid mix the git history. Is that OK?

**Comment by holgerbrandl** [comment] 2018-12-16 10:13
Sure. If possible keep the new PR as focused as possible to easy merging.

**Comment by holgerbrandl** [comment] 2019-06-24 20:30
Windows support has improved considerably (still relies on gitbash but this is per design), so I'm closing this ticket.

**Closed by holgerbrandl** 2019-06-24 20:30 UTC

**Comment by pmatysek** [comment] 2021-09-30 11:08
Can someone give me advice how to use kscript on Windows?
I should add to the secript something like that?
`#!C:\Program Files\Git\git-bash.exe kscript`

It shows me error `[kscript] [ERROR] kotlinc is not in PATH`, but kotlinc surely is in PATH

**Comment by holgerbrandl** [comment] 2021-09-30 13:58
As the error says, kotlin does not seem to be in your PATH.
