### ISSUE TITLE
Class org.apache.kafka.common.serialization.StringSerializer could not be found

### ISSUE THREAD

**Issue by csyj501** [holgerbrandl/kscript#204] opened 2018-12-15 06:38 UTC
`
#! /usr/bin/env kscript
//DEPS org.apache.kafka:kafka_2.12:2.1.0
//@file:DependsOn("org.apache.kafka:kafka_2.12:2.1.0")

import java.util.Properties;

import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer

val x = org.apache.kafka.common.serialization.StringSerializer()
println(x)
val properties = Properties()
properties["bootstrap.servers"] = "192.168.1.8:9092"
properties["acks"] = "all"
properties["retries"] = 0
properties["batch.size"] = 16384
properties["linger.ms"] = 1
properties["buffer.memory"] = 33554432
properties["key.serializer"] = StringSerializer::class.java.name
properties["value.serializer"] = StringSerializer::class.java.name

val producer = KafkaProducer<String,String>(properties)
producer.send(ProducerRecord("test", "test"))
println("ok")
producer.close()
`

[root@bogon:/root/yangguo/kotlin/code/script]$./kafkaTest.kts 
==============================================================
org.apache.kafka.common.serialization.StringSerializer@7ba4f24f
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at Main_KafkaTest$Companion.main(Main_KafkaTest.kt:6)
	at Main_KafkaTest.main(Main_KafkaTest.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serialization.StringSerializer for configuration key.serializer: Class org.apache.kafka.common.serialization.StringSerializer could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:718)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:471)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:464)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:392)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:301)
	at KafkaTest.<init>(kafkaTest.kts:24)
	... 13 more

**Comment by holgerbrandl** [comment] 2018-12-18 12:32
Duplicate of #131

**Comment by holgerbrandl** [comment] 2018-12-18 12:33
You may want to vote on the youtrack issue as well because it's a platform issue.

**Closed by holgerbrandl** 2018-12-18 12:32 UTC
Labels: bug
