### ISSUE TITLE
Undocumented requires  java 1.9

### ISSUE THREAD

**Issue by DALDEI** [holgerbrandl/kscript#62] opened 2017-11-19 07:41 UTC
When running with oracle jdk 1.8u144

java 1.8
```
[0][@idell ~]$ java -version                                                                                                                                                                  
java version "1.8.0_144"                                                                                                                                                                      
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)                                                                                                                                         
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)                                                                                                                              

0][@idell ~]$ kscript 'println("hi")'
Exception in thread "main" java.lang.UnsupportedClassVersionError: Main_Scriptlet_6ddfb6e25d6c9300 has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:39)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)

```
java 1.9

```

[0][@idell ~]$ JAVA_HOME=/usr/java/jdk-9.0.1
[0][@idell ~]$ pathmunge $JAVA_HOME/bin
[0][@idell ~]$ java -version                                                                                                                                                       
java version "9.0.1"                                                                                                                                                                          
Java(TM) SE Runtime Environment (build 9.0.1+11)                                                                                                                                              
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)                                                                                                                                
[0][@idell ~]$ !ks
kscript 'println("hi")'
hi
```

**Comment by holgerbrandl** [comment] 2017-11-20 08:39
I've checked the `kscript` binaries and they have a targetCompatibility of 1.6 (because of the default of the kotlin gradle task).

The reason for the observed problem is (most likely) that you've switched between java versions while using kscript. I guess your ran you _demo_ with java9 once and now switched back to java8. But since kscript is caching compiler jars, you get the error.

As a simple workaround, you could clear the cache with `kscript --clear-cache`. Alternatively, 
you try something "new", such as `kscript "println(12345)"`

Not sure if it's a but, but at least it's something we could take care of within `kscript`. I think the fix should be changing the cached jar file name to include the java compiler version (as defined by $PATH or JAVA_HOME). What do you think?

**Comment by DALDEI** [comment] 2017-11-22 20:12
Clearing the cache '<duh>' -- hadnt thought of that.
Unfortunately didn't help.

```
[1][@idell app]$ java -version 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
[0][@idell app]$ kscript --clear-cache
Cleaning up cache...
[0][@idell app]$ kscript 'println("hi")'
Exception in thread "main" java.lang.UnsupportedClassVersionError: Main_Scriptlet_6ddfb6e25d6c9300 has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:39)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
[1][@idell app]$ 
```

**Comment by holgerbrandl** [comment] 2017-11-22 20:14
Just to be on the save side: `javac -version`?

**Comment by DALDEI** [comment] 2017-11-22 20:16
Thanks for the tip.  Clearing the cache didnt work nor did uninstalling jdk9 -- but some find/greps and I found $HOME/.kscript/scriptlet.xxxxxx.jar
Removing $HOME/.kscript worked !

As for you suggestion:  Yes I think that kscript cache's and other things that potentially depend on the platform language, version, implementation should be separated.
For caches -- suggest separating not by version only but by language version and compiler version/implementation.   Some compilers are cross compatible some are not (without care).
e.g the IBM Java compiler can produce or require dependencies which dont work with Oracle,
OpenJDK and Oracle java compiler produce compatible byte-codes to my knowledge but may have non compatible or non existent dependencies.  Not sure if your caching transitive dependencies.

**Comment by DALDEI** [comment] 2017-11-22 20:22
Related Question:  can kscript produce _Deployable binaries__  ?  I've had problems trying to figure out all the dependencies of a kscript so that I can make a docker image that runs kscript ( shy of installing everything a dev environment might need )

While I like the feature of late-binding via maven -- I dont want to have to include maven and the world it then pulls in for a deployed script.   So either I need to find and specify all the dependencies, or have kscript or kotlinc do so, and produce a compiled script or a (possibly pre-processed) script that is dependency complete.

Thinking something similar to a gradelw 'init' script that produces a shadow jar or runnable application or lib distribution that can be run in the dev env (or a well endowed release server) -- then zip'd and sent/installed/deployed to a runtime  environment (like docker, AWS Lambdas , VM  or simply as a component dependency of another app)

**Comment by holgerbrandl** [comment] 2017-11-22 22:53
That's a lot of questions for a single ticket.

1. I find it concerning that `--clear-cache` did not work. I don't see any reason for that. See yourself https://github.com/holgerbrandl/kscript/blob/v2.2.1/src/main/kotlin/kscript/app/Kscript.kt#L76
Could you check if the problem is reproducible by running  somthing like ` rm -rf ~/.kscript && kscript "println(42)" && kscript --clear-cache && ls -la ~/.kscript` ?

2. I've tried to address the target compatibility problem by also using kotlinc (which is targetting 1.6 by default) for the script wrapper. This should also make kscript a bit faster because we can save one external tool call. By doing so I think that the cache can remain as simple as it is for now. Not sure if IBM's compiler would work with kotlin anyway?

4. Concerning deployable binaries. Most importantly, `kscript` runs well within docker, vms, etc, so the easiest solution would be to just put `kscript` into your container, and move around simple kscripts. That's also its core idea: "build fully self-contained mini-applications within a single file". Thus adding another deployment-level already seems a bit off/wrong to me.

Anyway, there's a related ticket https://github.com/holgerbrandl/kscript/issues/63 but don't think that it covers your specific use case. Personally, I would also prefer your idea of shadow-jaring the compiled script along with its dependencies. However, when doing so we would lose the runtime configuration which can be specified via `//KOTLIN_OPTS`/`@file:KotlinOpts()`, because there's notway to write it into a jar.

What we should avoid imho is to build another gradle/maven with kscript. Clearly, it implements some aspects of a build tool, but by design, it's more a script interpreter.

**Comment by holgerbrandl** [comment] 2017-12-01 22:18
I've copied the deployment bits into 63 and closing this ticket because compatibility issues have been addressed in master, and I can't reproduce the cache clearing problem.

**Closed by holgerbrandl** 2017-12-01 22:18 UTC
