### ISSUE TITLE
Not able to run kotlin script in intellij with dependencies

### ISSUE THREAD

**Issue by yhjhoo** [holgerbrandl/kscript#128] opened 2018-06-03 15:08 UTC
Here is my code

test.kts
```
#!/usr/bin/env kscript
import org.apache.commons.lang3.StringUtils

//DEPS org.apache.commons:commons-lang3:3.6

var a = "hello"
val result = StringUtils.isAllLowerCase(a)

println("result: ${result}")
```
Open in intellij
$ kscript --idea test.kts

When I hit intellij run button, it throws error that org.apache.commons.lang3.StringUtils not found.

**Comment by holgerbrandl** [comment] 2018-06-04 07:35
Can you open the generated gradle file of the temporary project? Are any errors reported by the IDE in here?

**Comment by yhjhoo** [comment] 2018-06-05 23:55
Didn't see any compile error in intellij

![image](https://user-images.githubusercontent.com/24640/41008689-f908dada-695e-11e8-8dc9-ba0d716d29bd.png)

**Comment by yhjhoo** [comment] 2018-06-06 00:04
There is no issue when I run it with kscript command

**Comment by holgerbrandl** [comment] 2018-06-06 08:32
The issue is not related to kscript but rather to the Intellij platform. See https://youtrack.jetbrains.com/issue/KT-11618 . According to the log it's supposed to be fixed in more recent plugin builds, but it does not work for me either. I've asked in the #scripting slack channel, let's see what they say.

**Closed by holgerbrandl** 2018-06-06 08:32 UTC
