### ISSUE TITLE
Unable to pull dependencies

### ISSUE THREAD

**Issue by andrealexandre** [holgerbrandl/kscript#238] opened 2019-08-26 15:59 UTC
I wrote a simple script with a simple dependency to 'com.opencsv:opencsv:4.6'.
I get the following error message:
```
[kscript] Resolving dependencies...
[kscript]     Resolving com.opencsv:opencsv:4.6...[kscript] [ERROR] Failed while connecting to the server. 
    Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. 
    If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: 
    failed to load 'com.opencsv:opencsv:jar:4.6 (runtime)' from 
        [
            "maven (https://maven.<company>.net/content/groups/public, releases+snapshots) without authentication", 
            "maven (https://maven.<company>.net/content/groups/public, releases+snapshots) without authentication"
        ] into /Users/<my_user>/.m2/repository
```

Is it possible to have a clearer error message on what could be causing this, the repository urls work perfectly on maven and gradle, and I can't seem to find a reason for kscript to fail on resolving the dependencies.

**Comment by holgerbrandl** [comment] 2019-08-26 21:54
I've tried to reproduce the problem with
```
//DEPS com.opencsv:opencsv:4.6

print("foo")
```

but the current version v2.8 of kscript works fine with it. Would you mind sharing a more complete example?

I agree that the error is a bit cryptic.

**Comment by andrealexandre** [comment] 2019-08-27 08:59
I suspect it could be something our company maven settings.xml file. let me clean it up and I'll post a similar example here.

**Comment by andrealexandre** [comment] 2019-08-27 09:12
Here it is, I strongly suspect the mirror element, since all our artifacts have to pass through a common repository. I suspect kscript dependency resolution is not taking this into account.
Let me know what you think, I would be more than happy to help figure this issue out.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                            http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <mirrors>
        <mirror>
            <id>maven</id>
            <mirrorOf>*</mirrorOf>
            <url>https://$maven_host/content/groups/public/</url>
        </mirror>
    </mirrors>
    <servers>
        <server>
            <id>maven</id>
            <username>$username</username>
            <password>$password</password>
        </server>
        <server>
            <id>releases</id>
            <username>$username</username>
            <password>$password</password>
        </server>
        <server>
            <id>snapshots</id>
            <username>$username</username>
            <password>$password</password>
        </server>        
    </servers>
    <profiles>
        <profile>
            <id>maven</id>
            <properties>
                <repository.url.releases>https://$maven_host/content/repositories/releases/</repository.url.releases>
                <repository.url.snapshots>https://$maven_host/content/repositories/snapshots/</repository.url.snapshots>
            </properties>
            <repositories>
                <repository>
                    <id>central</id>
                    <url>http://central</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>central</id>
                    <url>http://central</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>maven</activeProfile>
    </activeProfiles>
</settings>
```

**Comment by holgerbrandl** [comment] 2019-08-27 18:25
Kscript has support for additional repositories via but it does not implement any mirror specific functionality.

To provide such functionality we would need to either find or setup a mirror repo to establish a unit/regression test. In addtion, we'd need a kscript example. Once the test is in place we can try to complement the current annotations if needed or change the internal resolver implementation.

**Comment by andrealexandre** [comment] 2019-08-27 18:37
Alright, I can take this ticket if you wouldn't mind. See if I can explore a solution for this use case.

**Comment by holgerbrandl** [comment] 2019-08-27 18:56
This would be great. Please let me know if you need help or in case you have any questions.

**Comment by andrealexandre** [comment] 2019-08-27 20:14
Thanks I appreciate it! Let me get familiarised with the code base first. I'll fire away any questions that pop up along the way.

**Comment by malachid** [comment] 2020-01-24 21:43
> I've tried to reproduce the problem with
> 
> ```
> //DEPS com.opencsv:opencsv:4.6
> 
> print("foo")
> ```
> 
> but the current version v2.8 of kscript works fine with it. Would you mind sharing a more complete example?
> 
> I agree that the error is a bit cryptic.

I was having the same problem. Can't resolve any dependencies.
So I tried that example you posted and got:

```
[kscript] Resolving dependencies...
[kscript]     Resolving com.opencsv:opencsv:4.6...[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'com.opencsv:opencsv:jar:4.6 (runtime)' from ["jcenter (http://jcenter.bintray.com/, releases+snapshots) without authentication"] into /Users/malachi.da/.m2/repository

```

**Comment by holgerbrandl** [comment] 2020-01-29 07:02
Hmm, afaik nothing has changed about dependency resolution between 2.9.0 and 2.9.3 but having an obsolete bug would be nice. What about you @andrealexandre?

**Comment by andrealexandre** [comment] 2020-02-11 18:24
@holgerbrandl I still have the same issue, since there's a workaround. 
This could be due to certain the each individual `~/.m2/settings.xml` which makes debug this issue a bit of a problem.
In my case, I proxying the dependency via a company owned maven repository, it's possible that the dependency solver it's able to deal with this.

**Comment by holgerbrandl** [comment] 2020-02-17 11:47
Given that the mirror support is not yet implemented, it makes total sense to me that your use case is not yet supported. You mentioned initially that you might be able to help by enhancing kscript's implementation in that regards. Do you still plan to do so?

**Comment by mirceanis** [comment] 2020-03-06 11:47
I'm running into the same (or a similar) issue with jitpack.

Here's a snippet that reproduces the problem:

```kotlin
#!/usr/bin/env kscript

@file:MavenRepository("jitpack","http://jitpack.io")
@file:DependsOn("com.github.uport-project.kotlin-common:signer-common:0.4.0")

import me.uport.sdk.signer.KPSigner

val signer = KPSigner("0x1234")
println("hello ${signer.getAddress()}")
```

Any suggested workarounds, or a hint on how it could be fixed?
I'd be willing to contribute a PR but I'm new to kscript and don't know where to start

**Comment by JDFind** [comment] 2020-03-07 21:31
+1 for a fix or workaround

**Comment by mirceanis** [comment] 2020-03-07 22:49
I managed to do some debugging and it lead me to post this issue: https://github.com/jcabi/jcabi-aether/issues/106

It may be too early to tell but it leads me to think it won't be fixed there.
Perhaps a new method of downloading the dependencies is worth investigating.

I'm ignorant when it comes to maven repos but from the looks of it it seems to boil down to a HTTP GET request. I'm sure I'm missing something but if I'm not it may not be very hard to replace.
Any thoughts or suggestions?

**Comment by holgerbrandl** [comment] 2020-03-09 22:31
Great work. Fingers crossed that they patch it soon so that we can release a new version of kscript including the fix.

**Comment by jantobola** [comment] 2020-04-02 10:26
Hi, I am currently getting this error over and over again, sometimes it resolves dependencies, but it is very slow. Is this reported issue related? I am not specifying custom maven repo, just DependsOn annotation. Is there any workaround? My scripts are unusable due to this issue right now. Thanks

`[kscript] Resolving dependencies...
 [kscript]     Resolving software.amazon.awssdk:aws-sdk-java:2.10.56...[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
 [kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'software.amazon.awssdk:aws-sdk-java:jar:2.10.56 (runtime)' from ["jcenter (https://jcenter.bintray.com/, releases+snapshots) without authentication"] into /root/.m2/repository`

**Comment by holgerbrandl** [comment] 2020-04-06 06:28
@jantobola Is this potentially a different topic then? Not sure if jcabi-aether allows to set such a parameter.

Any news on the aether fix @mirceanis

**Comment by mirceanis** [comment] 2020-04-06 09:57
@holgerbrandl no news there.
The aether project has very low activity since 2017 so I don't expect a fix there.

Perhaps a new dependency download tool is necessary.
I don't know of any alternatives. Gradle seems to do a great job, perhaps it's a valid lead.

**Comment by martinbonnin** [comment] 2020-05-04 23:28
+1 a better way to pull dependencies. I came here because I had this error:

```
[kscript]     Resolving com.dailymotion.kinta:kinta-lib:0.1.10...[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'com.dailymotion.kinta:kinta-lib:jar:0.1.10 (runtime)' from ["jcenter (https://jcenter.bintray.com/, releases+snapshots) without authentication"] into /Users/m.bonnin/.m2/repository```

The error was actually a transitive dependency requiring an additional repo:

```
@file:MavenRepository("gradle-releases", "https://repo.gradle.org/gradle/libs-releases-local/")
```
But tthe error didn't say anything about that. 

I'm not sure if this can be fixed without a patch in `jcabi-aether`...
Also, it looks like `jcabi-eather` doesn't play super well with Java 11 (#239).

For what it's worth, the kotlin-main-kts resolver code is there:
 
https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-main-kts/src/org/jetbrains/kotlin/mainKts/impl/ivy.kt

But it looks like it has even more limitations:
https://youtrack.jetbrains.com/issue/KT-38212
https://youtrack.jetbrains.com/issue/KT-38006

So maybe Gradle is a good candidate... Or forking aether ? Or rewriting a new one ?

**Comment by aimeejtix** [comment] 2020-05-13 09:40
I'm seeing this error but only on certain dependencies that I try to access. 
I have custom artifactory that I pull dependencies from. There are multiple versions of the same artefact that I am trying to pull but for some reason I can only resolve some of them. 

This one resolves for example (updated with generic values):
```
@file:MavenRepository("my-art", "https://myartifactory.jfrog.io/myartifactory/gradle-dev-local", user="{{ARTIFACTORY_USR}}", password="{{ARTIFACTORY_PSW}}")
@file:DependsOnMaven("com.myproject.test-helpers:test-helpers:0.0.1")
```
But this one doesn't (note the version change on the last line):
```
@file:MavenRepository("my-art", "https://myartifactory.jfrog.io/myartifactory/gradle-dev-local", user="{{ARTIFACTORY_USR}}", password="{{ARTIFACTORY_PSW}}")
@file:DependsOnMaven("com.myproject.test-helpers:test-helpers:0.0.3")
```
This it what artifactory looks like:
![image](https://user-images.githubusercontent.com/38347225/81796428-5617d900-9505-11ea-9a88-5d2b58cddfac.png)

And the 2 dependencies in question:
![image](https://user-images.githubusercontent.com/38347225/81796636-9f682880-9505-11ea-91ea-8dae70e2e64f.png)
![image](https://user-images.githubusercontent.com/38347225/81796673-adb64480-9505-11ea-973c-8f6b3b695127.png)

The only thing I can spot id the size difference, but surely it's not big enough to cause this issue? 

Really hoping for a solution on this so posting in case it helps any investigations! 
Is there a way around this for now? Is it possible to set a custom dependency manager by using the old way?

**Comment by jiraguha** [comment] 2020-05-13 10:23
I had the same issue today with `//DEPS org.javamoney:moneta:1.3`! I am pretty sure it was on maven-central. At the end I have added another Maven Repository to make it work: `@file:MavenRepository("releases", "https://bintray.com/javamoney/maven/")`

It can be a annoying bug if you do not find a fallback repo.

**Comment by victorraft** [comment] 2020-11-10 14:45
I lost a few hours because of this. Looks like all of the repos I tried didn't work because of this issue.
Anyone know how do I import the clikt repo, for example? Could not get it (and others) to work... I'm afraid if this isn't fixed kscript is not an option for my company :( 
Any idea when it will be fixed?

**Comment by holgerbrandl** [comment] 2020-11-10 17:29
At least the jitpack example from @mirceanis as well as the initial opencsv example  by @andrealexandre work fine when using the new kotlin-scripting-based resolver which you can find/test in branch https://github.com/holgerbrandl/kscript/tree/fix239

I'm closing this ticket because it's covering too many individual examples. Please submit the other examples (which may relate to entirely different root causes) as separate issues. Thank you for your understanding.

**Closed by holgerbrandl** 2020-11-10 17:29 UTC
Labels: bug, enhancement, help wanted
