### ISSUE TITLE
How to use a local jar file as dependency?

### ISSUE THREAD

**Issue by hqzxzwb** [holgerbrandl/kscript#212] opened 2019-02-18 10:44 UTC
Anything like @file:DependsOn("XXX.jar")?

**Comment by holgerbrandl** [comment] 2019-02-18 13:44
This wont work. You could install the jar into the local maven repo. See https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

**Comment by matthid** [comment] 2019-02-23 12:29
```kotlin

@file:MavenRepository("local-rep","file:///path/to/local/maven/dir" )

```

Then write a pom file (or copy from maven) and copy the jar and the pom into the correct directory.
For `org.myorg:mypackage:1.0-my` 
  -> `/path/to/local/maven/dir/org/myorg/mypackage/1.0-my/mypackage-1.0-my.jar`
  -> `/path/to/local/maven/dir/org/myorg/mypackage/1.0-my/mypackage-1.0-my.pom`

**Comment by holgerbrandl** [comment] 2019-02-25 12:10
AFAIK you don't need to declare the local maven repo. It's included by default. So installing a jar into the local repo should be sufficient.

**Comment by DALDEI** [comment] 2019-04-19 04:08
I simply cannot get this to work at all. 
No MavenRepository with file url resolves to anything I have thrown at it

**Comment by DALDEI** [comment] 2019-04-22 05:50
FYI:  installing to maven local doesnt work for me either

```
[kscript] Resolving dependencies...
[kscript]     Resolving nexstra.nconnect:sftp:1.3...[kscript] [ERROR] Failed to lookup dependencies. Check dependency locators or file a bug on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'nexstra.nconnect:sftp:jar:1.3 (compile)' from ["jcenter (http://jcenter.bintray.com/, releases+snapshots) without authentication"] into /home/dlee/.m2/repository

```

Not sure what the 'into ...' means but its not looking IN mavenLocal

 header of kscript
`
@file:DependsOn("nexstra.nconnect:sftp:1.3")
`

also tried

@file:DependsOnMaven("nexstra.nconnect:sftp:1.3")

**Comment by holgerbrandl** [comment] 2019-06-17 07:12
Are you using the latest v2.8.0? There was an issue with dependency resolving in 2.7.0 which was fixed in 2.7.1.

**Comment by zhuker** [comment] 2019-06-23 20:22
any way to specify classpath eg `kscript -cp myjar.jar myscript.kts` ?

**Comment by holgerbrandl** [comment] 2019-06-24 20:33
Duplicate of #127

**Comment by holgerbrandl** [comment] 2019-06-24 20:33
@zhuker No, because it contradicts the design to write self-contained mini-applications. However, you could follow the advice from above and install it into your local m2 maven index.

**Closed by holgerbrandl** 2019-06-24 20:33 UTC

**Comment by wuseal** [comment] 2019-08-02 13:15
@holgerbrandl  Great Project! And When I update the Kotlin library code And need I upgrade the version of the library to publish it to LocalMavenReop? Or just override is OK, Or need clean the cache? If I could override the local maven without clean, That seems very convenient for we do not need to modify the *.kts where : `@file:DependsOn("wu.seal.kscript:log:1.0")` ->  `@file:DependsOn("wu.seal.kscript:log:1.1")`

**Comment by holgerbrandl** [comment] 2019-08-05 21:49
@wusal republishing to your local maven repo should be sufficient. No need to clean the cache. You also don't have to increment the version number (although it would be good practice if you have used the artefact elsewhere meanwhile).

**Comment by wuseal** [comment] 2019-08-05 23:32
@holgerbrandl Got it, TKS:smile:
