### ISSUE TITLE
@file:KotlinOpts("--module-path") @file:KotlinOpts("--add-modules java.sql") doesn't seem to work w/ JDK11

### ISSUE THREAD

**Issue by kenyee** [holgerbrandl/kscript#307] opened 2021-02-25 14:02 UTC
Trying to use this because when I run w/ JDK11, GSon can't find java.sql.Time.

I get this error:
 error: unsupported argument: --add-modules

Is there any way to add this module if >JDK8 is detected?

**Comment by holgerbrandl** [comment] 2021-03-11 09:42
I think to pass an argument directly the JVM you need to prefix it with -J. See `kotlin -help`

**Comment by holgerbrandl** [comment] 2021-04-25 11:58
Duplicate of https://github.com/holgerbrandl/kscript/issues/163

**Closed by holgerbrandl** 2021-04-25 11:58 UTC
