### ISSUE TITLE
Jcenter no longer supports HTTP, only HTTPS

### ISSUE THREAD

**Issue by mmdango** [holgerbrandl/kscript#254] opened 2020-01-13 18:37 UTC
The default repository listed [here](https://github.com/holgerbrandl/kscript/blob/aac75afea0a25f8cbd9c0340548e56878b61ea9f/src/main/kotlin/kscript/app/DependencyUtil.kt#L85) will cause dependency fetch failures due to Jcenter no longer support HTTP 

![image](https://user-images.githubusercontent.com/6417185/72282014-a2531b00-35f0-11ea-9fe2-55da05a37fe0.png)

**Comment by ilanpillemer** [comment] 2020-01-14 09:10
this seems to effect all versions... 😢

**Comment by kaustavj** [comment] 2020-01-14 09:21
For now you can use:
   
@file:MavenRepository("jcenter","https://jcenter.bintray.com")

**Comment by ilanpillemer** [comment] 2020-01-14 09:49
`[kscript] Resolving dependencies...[kscript] [ERROR] Failed to lookup dependencies. Check dependency locators or file a bug on https://github.com/holgerbrandl/kscript
[kscript] The error reported by maven was:
[kscript] [mvn] [INFO] Scanning for projects...
[kscript] [mvn] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[kscript] [mvn] [ERROR] 'repositories.repository.id' must be unique: jcenter -> http://jcenter.bintray.com/ vs https://jcenter.bintray.com @ line 20, column 17
[kscript] [mvn]  @ 
[kscript] [mvn] [ERROR] The build could not read 1 project -> [Help 1]
[kscript] [mvn] [ERROR]   
[kscript] [mvn] [ERROR]   The project kscript:maven_template:1.0 (/tmp/__resdeps__temp__2902151751028993012_pom.xml) has 1 error
[kscript] [mvn] [ERROR]     'repositories.repository.id' must be unique: jcenter -> http://jcenter.bintray.com/ vs https://jcenter.bintray.com @ line 20, column 17
[kscript] [mvn] [ERROR] 
[kscript] [mvn] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[kscript] [mvn] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[kscript] [mvn] [ERROR] 
[kscript] [mvn] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[kscript] [mvn] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[kscript] [mvn] 
[kscript] Generated pom file was:`

That didn't work.. 😢

**Comment by mmdango** [comment] 2020-01-14 18:30
@ilanpillemer That error looks like you just need to rename the `"jcenter"` part

`'repositories.repository.id' must be unique: jcenter -> http://jcenter.bintray.com/ vs https://jcenter.bintray.com @ line 20, column 17`

**Comment by ilanpillemer** [comment] 2020-01-14 19:39
That's precisely the point. You need to replace jcenter, which did not work.

**Comment by ilanpillemer** [comment] 2020-01-16 15:27
@holgerbrandl I see the pull request has been merged.. when will a version be released with the hot fix?

**Comment by holgerbrandl** [comment] 2020-01-17 07:22
I've released v2.9.3 including the fix to all channels. Thanks for your help and patience.

**Closed by holgerbrandl** 2020-01-17 07:22 UTC

**Comment by ilanpillemer** [comment] 2020-01-19 16:51
Thanks! Looks like upgrading to latest version did not introduce regression errors on the deployed code.
