### ISSUE TITLE
Support dynamic dependencies / Support for gradle repository features

### ISSUE THREAD

**Issue by DALDEI** [holgerbrandl/kscript#156] opened 2018-09-05 15:00 UTC
I make heavy use of gradle dynamic versions.  These produce pom files that kscript is not resolving correctly.   example      
`
[ERROR] Failed to execute goal on project maven_template: Could not resolve dependencies for project kscript:maven_template:jar:1.0: The following artifacts could not be resolved: org.jetbrains.kotlinx:kotlinx-html:jar:0.6.4, org.apache.logging.log4j:log4j-api:jar:2.8.+, org.apache.logging.log4j:log4j-core:jar:2.8.+, org.apache.logging.log4j:log4j-jcl:jar:2.8.+: Could not find artifact org.jetbrains.kotlinx:kotlinx-html:jar:0.6.4 in jcenter (http://jcenter.bintray.com/) -> [Help 1]`

If I change my build to explictly use a version # then it works.  Its not a simple option to do that globally.

Suggestion:  support a 'GradleRepository' or "DependsOnGradle'  or IvyRepository annotation.

gradle should be fairly easy given the existing souce that generates a POM and existing source that generates gradle build package.  In fact if I comment the offending dependency then run

kscript --idea   myscript.kts  

then put it back into the build.gradle it works fine.

Alternative/Suppliment -- allow 'kscript --idea'  and --package to NOT first compile the kscript -- just generate the build.gradle (and optionally the package structure.)
That doesnt solve runtime problems but it should allow --package to work

**Comment by holgerbrandl** [comment] 2018-09-05 15:12
Could you provide a script example with a public dynamic dependency so that I could reproduce the problem?

**Comment by holgerbrandl** [comment] 2018-09-25 07:54
Duplicate of #166

**Closed by holgerbrandl** 2018-09-25 07:54 UTC
