### ISSUE TITLE
"kscript -p" for printing like Perl 

### ISSUE THREAD

**Issue by lathspell** [holgerbrandl/kscript#172] opened 2018-10-01 21:32 UTC
While reading http://holgerbrandl.github.io/kotlin/2017/05/08/kscript_as_awk_substitute.html I wondered why there is not "-p" argument like in Perl that makes it print the outcome of the last expression. Or wraps everything in a "println( ... )".

Old:

    kscript -t 'println( lines.count { it.matches(Regex(".*N80.JB.*")) } )' some_flights.tsv

New:

    kscript -p -t 'lines.count { it.matches(Regex(".*N80.JB.*")) }' some_flights.tsv

**Comment by holgerbrandl** [comment] 2018-10-02 09:57
Duplicate of #110, see my arguments there.

What we potentially could/should do, is to add a generic `Any.print` extension the text support library to streamline the flow a bit.

**Comment by lathspell** [comment] 2018-10-02 11:30
What about:
If the input contains a ";" then wrap the last term with "print( ... )" else wrap everyhing with "print( ... )"

**Comment by holgerbrandl** [comment] 2018-10-02 11:59
This seems rather hacky to me. If it all we would need to parse the kotlin script into a DOM check if there's just one top-level expression. But since parsing process would add a lot to the overall overhead time of kscript at the moment I guess.
I may be feasible to do so more easily once kscript has been migrated to the new scripting architecture coming with kotlin v1.3.

**Comment by holgerbrandl** [comment] 2018-10-29 08:50
Won't fix for now. Feel welcome to keep commenting on this thread.

**Closed by holgerbrandl** 2018-10-29 08:50 UTC
