### ISSUE TITLE
Dependency importing is not working, full code and error shown

### ISSUE THREAD

**Issue by lfmunoz** [holgerbrandl/kscript#235] opened 2019-08-06 18:34 UTC
Error:
```
~$ kscript src/MainApp.kts
[kscript] Dependencies resolved
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at Main_MainApp$Companion.main(Main_MainApp.kt:6)
        at Main_MainApp.main(Main_MainApp.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:110)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:120)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: javax.ws.rs.core.Form$1
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:325)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:443)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy10.grantToken(Unknown Source)
        at org.keycloak.admin.client.token.TokenManager.grantToken(TokenManager.java:89)
        at org.keycloak.admin.client.token.TokenManager.getAccessToken(TokenManager.java:69)
        at org.keycloak.admin.client.token.TokenManager.getAccessTokenString(TokenManager.java:64)
        at org.keycloak.admin.client.resource.BearerAuthFilter.filter(BearerAuthFilter.java:52)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:590)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:440)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy18.create(Unknown Source)
        at MainApp.createUser(MainApp.kts:257)
        at MainApp.<init>(MainApp.kts:88)
        ... 13 more
Caused by: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: javax.ws.rs.core.Form$1
        at org.jboss.resteasy.core.interception.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:38)
        at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:146)
        at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:121)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:398)
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.writeRequestBodyToOutputStream(ApacheHttpClient4Engine.java:671)
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.buildEntity(ApacheHttpClient4Engine.java:636)
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.loadHttpMethod(ApacheHttpClient4Engine.java:514)
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:313)
        ... 30 more

```

Source Code:

```
#!/usr/bin/env kscript


//@file:Include("KeycloakAPI.kts")
@file:CompilerOpts("-jvm-target 1.8")
@file:KotlinOpts("-J-Xmx1g")

@file:DependsOn("com.fasterxml.jackson.core:jackson-annotations:2.9.9")
@file:DependsOn("com.fasterxml.jackson.core:jackson-core:2.9.8")
@file:DependsOn("com.fasterxml.jackson.core:jackson-databind:2.9.8")
@file:DependsOn("com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.9.8")
@file:DependsOn("com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.9.8")
@file:DependsOn("com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.9.8")
@file:DependsOn("com.github.fge:btf:1.2")
@file:DependsOn("com.github.fge:jackson-coreutils:1.6")
@file:DependsOn("com.github.fge:json-patch:1.9")
@file:DependsOn("com.github.fge:msg-simple:1.1")
@file:DependsOn("com.github.stephenc.jcip:jcip-annotations:1.0-1")
@file:DependsOn("com.google.guava:guava:16.0.1")
@file:DependsOn("commons-codec:commons-codec:1.11")
@file:DependsOn("commons-io:commons-io:2.5")
@file:DependsOn("commons-logging:commons-logging:1.2")
@file:DependsOn("javax.activation:activation:1.1.1")
@file:DependsOn("javax.validation:validation-api:2.0.1.Final")
@file:DependsOn("org.apache.httpcomponents:httpclient:4.5.6")
@file:DependsOn("org.apache.httpcomponents:httpcore:4.4.10")
@file:DependsOn("org.bouncycastle:bcpkix-jdk15on:1.56")
@file:DependsOn("org.bouncycastle:bcprov-jdk15on:1.56")
@file:DependsOn("org.jboss.logging:jboss-logging:3.3.2.Final")

@file:DependsOn("org.jboss.resteasy:resteasy-jaxrs:3.8.1.Final")
@file:DependsOn("org.jboss.resteasy:resteasy-client:3.8.1.Final")
@file:DependsOn("org.jboss.resteasy:jaxrs-api:3.0.12.Final")
@file:DependsOn("org.jboss.resteasy:resteasy-jaxb-provider:3.8.1.Final")
@file:DependsOn("org.jboss.resteasy:resteasy-jackson2-provider:3.8.1.Final")
//@file:DependsOn("org.jboss.resteasy:resteasy-jackson2-provider:3.8.1.Final")

@file:DependsOn("org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:1.0.1.Final")
@file:DependsOn("org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:1.0.3.Final")
@file:DependsOn("org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:1.0.1.Final")
@file:DependsOn("org.jetbrains.kotlin:kotlin-reflect:1.2.71")
@file:DependsOn("org.jetbrains.kotlin:kotlin-stdlib:1.2.71")
@file:DependsOn("org.jetbrains.kotlin:kotlin-stdlib-common:1.2.71")
//@file:DependsOn("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71")
@file:DependsOn("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71")
@file:DependsOn("org.jetbrains:annotations:13.0")
@file:DependsOn("org.keycloak:keycloak-admin-client:3.4.3.Final")
@file:DependsOn("org.keycloak:keycloak-common:3.4.3.Final")
@file:DependsOn("org.keycloak:keycloak-core:3.4.3.Final")
@file:DependsOn("org.reactivestreams:reactive-streams:1.0.2")

import org.keycloak.OAuth2Constants
import org.keycloak.admin.client.Keycloak
import org.keycloak.admin.client.KeycloakBuilder
import org.keycloak.admin.client.resource.RealmResource
import org.keycloak.representations.idm.*



val serverUrl = "http://localhost:9089/auth"
val realm = "ECO"
val username = "admin"
val password = "admin"
val clientId = "admin-cli"



val    keycloak = KeycloakBuilder.builder() //
        .serverUrl(serverUrl) //
        .realm(realm) //
        //.grantType(OAuth2Constants.CLIENT_CREDENTIALS) //
        .grantType(OAuth2Constants.PASSWORD) //
        .clientId(clientId) //
        //   .clientSecret(clientSecret) //
        .username(username)
        .password(password)
        ///   .resteasyClient(
        //          ResteasyClientBuilder()
        //                    .connectionPoolSize(10).build()
        //  )
        .build()
val     ecoRealm = keycloak.realm(realm)

//________________________________________________________________________________
// Step 1. Create user "super" with password "bh"
//________________________________________________________________________________ 
//kcManager.deleteUser("super")
val userId = createUser(ecoRealm,"super", "bh")


fun createUser(ecoRealm: RealmResource, username: String, password: String) : String {
    val user : UserRepresentation = UserRepresentation()
    user.username = username
    user.isEnabled = true
    val response = ecoRealm.users().create(user)
    val userId = response.location.path.substring(response.location.path.lastIndexOf('/') + 1)
    // Define password credential
    val passwordCred = CredentialRepresentation()
    passwordCred.isTemporary = false
    passwordCred.type = CredentialRepresentation.PASSWORD
    passwordCred.value = password
    // Set password credential
    ecoRealm.users().get(userId).resetPassword(passwordCred)
    return userId
}
```

Version   : v2.7.1

I have all those dependencies because that code is working with regular Kotlin and in intellij I copied pasted all the dependencies it was showing. 

In regular compiled kotlin my gradle file is as following (which is working)

```

def resteasyVersion = "3.8.1.Final" // 3.0.24.Final
def keycloakVersion = "3.4.3.Final"  // 3.4.3.Final




dependencies {
	compile group: 'commons-logging', name: 'commons-logging', version: '1.2'
	
	//implementation 'org.springframework.boot:spring-boot-starter-actuator'
	//implementation 'org.springframework.boot:spring-boot-starter-security'
	//implementation 'org.springframework.boot:spring-boot-starter-webflux'
	//implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
	implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'

// https://mvnrepository.com/artifact/org.jboss.resteasy/resteasy-client
    compile group: 'org.jboss.resteasy', name: 'resteasy-client', version: "$resteasyVersion"
    compile group: 'org.jboss.resteasy', name: 'resteasy-jaxrs', version: "$resteasyVersion"
    compile group: 'org.jboss.resteasy', name: 'resteasy-jackson2-provider', version: "$resteasyVersion"
	// https://mvnrepository.com/artifact/org.keycloak/keycloak-admin-client
    
    
    // https://mvnrepository.com/artifact/org.keycloak/keycloak-admin-client/3.4.3.Final
	compile group: 'org.keycloak', name: 'keycloak-admin-client', version: '3.4.3.Final'


	//runtimeOnly 'org.springframework.boot:spring-boot-devtools'
	//runtimeOnly 'com.h2database:h2'
	//testImplementation 'org.springframework.boot:spring-boot-starter-test'
	//testImplementation 'io.projectreactor:reactor-test'
	//testImplementation 'org.springframework.security:spring-security-test'
}
```

**Comment by holgerbrandl** [comment] 2019-08-08 12:41
Do you use the same java version? Maybe it's a module-system related, and you're using java>8 along with kscript.

A similar problem was reported under https://stackoverflow.com/questions/48584014/javax-ws-rs-processingexception-could-not-find-writer-for-content-type-applicat?noredirect=1&lq=1  . Maybe this helps to track down the cause. There are also more google hits with the error message, so it seems to be a problem that is independent of kotlin/kscript.

Without much testing, I'd think it's another flavour of the dodgy kotlin script class loader (which is used by kscript under the hood). See #131. 

I'll try to reproduce the problem later this week.

**Comment by lfmunoz** [comment] 2019-08-09 19:32
Problem is not independent of kotlin/kscript.  It works with kotlin exact code doesn't work kscript. 

I think you are right that the problem is something with the kotlin script class loader.

**Comment by holgerbrandl** [comment] 2019-08-19 20:20
I've tried and the problem is (assuming your code is legit and working) a kotlin platform bug:
![image](https://user-images.githubusercontent.com/200952/63296035-01e80d00-c283-11e9-9763-efb222024456.png)

See attached example project (created with kscript --idea and stripped down to remove kscript)
[tickket235_example.zip]
(https://github.com/holgerbrandl/kscript/files/3517511/tickket235_example.zip)
When running the script (using run from context menu) in Idea you get the same error.

So if needed please file a ticket under https://youtrack.jetbrains.com/oauth?state=%2Fissues%2FKT instead. Feel welcome to cross-ref it in this thread.

I'm closing this for now since it does not seem to be a kscript issue. Feel welcome to keep commenting on it.

**Closed by holgerbrandl** 2019-08-19 20:20 UTC
Labels: help wanted, question

**Comment by lfmunoz** [comment] 2019-08-22 22:51
@holgerbrandl  I started having the same problem when I generated a fat jar and tracked down the problem (Note: it was working with intellij). 

I mentioning it here to you because maybe you can create a fix for kscript by knowing this. 

Basically what I found out is that these two libraries

resteasy-client
resteasy-jaxrs

If you look in inside of the jars they both have the following file
META-INF/services/javax.ws.rs.ext.Providers

They have different content. Shadow jar was overwriting the content, but it needs to be merged.  How does kscript handle that?

**Comment by holgerbrandl** [comment] 2019-08-23 07:50
Thanks @lfmunoz for sharing your insights. 

We only use the shadow-jar when using `--package` option. Otherwise, individual jars are simply provided as class-path arguments to kotlin. So with respect to this issue, I still think that it is a platform issue and not a kscript bug.
